# Generated by Django 3.1.7 on 2021-03-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soldgoods',
            options={'ordering': ['goods'], 'verbose_name': 'Проданный товар', 'verbose_name_plural': 'Проданные товары'},
        ),
        migrations.RemoveField(
            model_name='soldgoods',
            name='sold_goods',
        ),
        migrations.AddField(
            model_name='soldgoods',
            name='goods',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='service.goods', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
